<a href="https://colab.research.google.com/github/castrokelly/PPGIa/blob/main/atividade_4_multiplicacao_matrizes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Aluna:** 40131556 - Kelly Christine Alvarenga de Castro (christine.kelly@pucpr.edu.br)  
**Mestrado / Turma:** PPGIa (404) 2026/02  
**Disciplina:** Fundamentos de Matemática Computacional (Turma ME)  
**Professor:** Dr. Vinícius Mourão Alves de Souza

# ATIVIDADE 4 — Multiplicação de Matrizes

## Objetivo

Implementar quatro funções para multiplicação de matrizes seguindo as perspectivas apresentadas na **Week 04**:

1. **Element perspective**
2. **Layer perspective**
3. **Column perspective**
4. **Row perspective**

As funções recebem duas matrizes $A$ e $B$, verificam se a multiplicação é válida e retornam a matriz resultante $C$.

Se $A$ possui dimensão $N \times M$ e $B$ possui dimensão $M \times K$, então a multiplicação é válida e o resultado $C = AB$ possui dimensão $N \times K$.


## 1. Importação da biblioteca

Será utilizado apenas o **NumPy**, com operações básicas compatíveis com os exemplos da disciplina, como `np.dot`, `np.outer`, multiplicação por escalar, soma de vetores e criação de matrizes com `np.zeros`.


In [1]:
import numpy as np

## 2. Verificação das dimensões

Antes da multiplicação, é necessário verificar se:

$$
\text{número de colunas de } A = \text{número de linhas de } B
$$

A função abaixo também verifica se as entradas são matrizes bidimensionais.


In [2]:
def validar_multiplicacao(A, B):
    A = np.asarray(A)
    B = np.asarray(B)

    if A.ndim != 2 or B.ndim != 2:
        raise ValueError("A e B devem ser matrizes bidimensionais.")

    if A.shape[1] != B.shape[0]:
        raise ValueError(
            f"Multiplicação inválida: A possui dimensão {A.shape} e B possui dimensão {B.shape}. "
            "O número de colunas de A deve ser igual ao número de linhas de B."
        )

    return A, B

## 3. Perspectiva por elemento — *Element perspective*

Nesta abordagem, cada elemento $c_{i,j}$ da matriz resultante é calculado separadamente pelo produto escalar entre:

- a linha $i$ de $A$;
- a coluna $j$ de $B$.

Matematicamente:

$$
c_{i,j} = \sum_{k=1}^{M} a_{i,k}b_{k,j}
$$

Assim, a matriz $C$ é preenchida **elemento por elemento**.


In [3]:
def multiplicacao_elemento(A, B):
    A, B = validar_multiplicacao(A, B)

    linhas_A = A.shape[0]
    colunas_B = B.shape[1]

    C = np.zeros((linhas_A, colunas_B), dtype=np.result_type(A, B))

    for i in range(linhas_A):
        for j in range(colunas_B):
            C[i, j] = np.dot(A[i, :], B[:, j])

    return C

## 4. Perspectiva por camadas — *Layer perspective*

Nesta perspectiva, o resultado é construído pela soma de **produtos externos**.

Para cada índice $k$:

- seleciona-se a coluna $k$ de $A$;
- seleciona-se a linha $k$ de $B$;
- calcula-se o produto externo com `np.outer`.

Cada produto externo gera uma camada com a mesma dimensão de $C$. A soma das camadas fornece o produto final:

$$
C = \sum_{k=1}^{M} A_{:,k} \otimes B_{k,:}
$$


In [4]:
def multiplicacao_camadas(A, B):
    A, B = validar_multiplicacao(A, B)

    linhas_A = A.shape[0]
    colunas_B = B.shape[1]
    numero_camadas = A.shape[1]

    C = np.zeros((linhas_A, colunas_B), dtype=np.result_type(A, B))

    for k in range(numero_camadas):
        camada = np.outer(A[:, k], B[k, :])
        C = C + camada

    return C

## 5. Perspectiva por colunas — *Column perspective*

Nesta abordagem, a matriz resultante é preenchida **coluna por coluna**.

Cada coluna de $C$ é uma combinação linear das colunas de $A$. Os pesos dessa combinação são os elementos da coluna correspondente de $B$:

$$
C_{:,j} = \sum_{k=1}^{M} b_{k,j}A_{:,k}
$$

Portanto, para cada coluna $j$ de $B$, combinamos as colunas de $A$ usando os valores de $B[:,j]$ como escalares.


In [5]:
def multiplicacao_colunas(A, B):
    A, B = validar_multiplicacao(A, B)

    linhas_A = A.shape[0]
    colunas_A = A.shape[1]
    colunas_B = B.shape[1]

    C = np.zeros((linhas_A, colunas_B), dtype=np.result_type(A, B))

    for j in range(colunas_B):
        for k in range(colunas_A):
            C[:, j] = C[:, j] + B[k, j] * A[:, k]

    return C

## 6. Perspectiva por linhas — *Row perspective*

Nesta abordagem, a matriz resultante é preenchida **linha por linha**.

Cada linha de $C$ é uma combinação linear das linhas de $B$. Os pesos utilizados são os elementos da linha correspondente de $A$:

$$
C_{i,:} = \sum_{k=1}^{M} a_{i,k}B_{k,:}
$$

Assim, cada elemento da linha de $A$ multiplica a linha correspondente de $B$.


In [6]:
def multiplicacao_linhas(A, B):
    A, B = validar_multiplicacao(A, B)

    linhas_A = A.shape[0]
    colunas_A = A.shape[1]
    colunas_B = B.shape[1]

    C = np.zeros((linhas_A, colunas_B), dtype=np.result_type(A, B))

    for i in range(linhas_A):
        for k in range(colunas_A):
            C[i, :] = C[i, :] + A[i, k] * B[k, :]

    return C

## 7. Geração de duas matrizes aleatórias

Serão utilizadas:

- uma matriz $A$ de dimensão $3 \times 2$;
- uma matriz $B$ de dimensão $2 \times 3$.

A multiplicação $AB$ é válida e deve produzir uma matriz $3 \times 3$.

A semente aleatória é fixada apenas para que o experimento possa ser reproduzido.


In [7]:
np.random.seed(42)

A = np.random.randint(0, 10, size=(3, 2))
B = np.random.randint(0, 10, size=(2, 3))

print("Matriz A:")
print(A)
print("Dimensão de A:", A.shape)

print("\nMatriz B:")
print(B)
print("Dimensão de B:", B.shape)

Matriz A:
[[6 3]
 [7 4]
 [6 9]]
Dimensão de A: (3, 2)

Matriz B:
[[2 6 7]
 [4 3 7]]
Dimensão de B: (2, 3)


## 8. Aplicação das quatro perspectivas

Agora as quatro funções são aplicadas às mesmas matrizes $A$ e $B$.


In [8]:
C_elemento = multiplicacao_elemento(A, B)
C_camadas = multiplicacao_camadas(A, B)
C_colunas = multiplicacao_colunas(A, B)
C_linhas = multiplicacao_linhas(A, B)

print("Resultado - Element perspective:")
print(C_elemento)

print("\nResultado - Layer perspective:")
print(C_camadas)

print("\nResultado - Column perspective:")
print(C_colunas)

print("\nResultado - Row perspective:")
print(C_linhas)

Resultado - Element perspective:
[[ 24  45  63]
 [ 30  54  77]
 [ 48  63 105]]

Resultado - Layer perspective:
[[ 24  45  63]
 [ 30  54  77]
 [ 48  63 105]]

Resultado - Column perspective:
[[ 24  45  63]
 [ 30  54  77]
 [ 48  63 105]]

Resultado - Row perspective:
[[ 24  45  63]
 [ 30  54  77]
 [ 48  63 105]]


## 9. Comparação com o operador padrão `@`

O NumPy permite calcular diretamente o produto matricial com o operador `@`:

```python
C = A @ B
```

Para verificar se todas as implementações fornecem o mesmo resultado, será utilizada a função `np.allclose`. Ela é adequada para comparações numéricas e também funciona caso as matrizes contenham valores reais.


In [9]:
C_padrao = A @ B

print("Resultado usando A @ B:")
print(C_padrao)

print("\nComparações com A @ B:")
print("Element perspective:", np.allclose(C_elemento, C_padrao))
print("Layer perspective:  ", np.allclose(C_camadas, C_padrao))
print("Column perspective: ", np.allclose(C_colunas, C_padrao))
print("Row perspective:    ", np.allclose(C_linhas, C_padrao))

resultados = [C_elemento, C_camadas, C_colunas, C_linhas]
todos_iguais = all(np.allclose(C, C_padrao) for C in resultados)

print("\nTodos os resultados são equivalentes:", todos_iguais)

Resultado usando A @ B:
[[ 24  45  63]
 [ 30  54  77]
 [ 48  63 105]]

Comparações com A @ B:
Element perspective: True
Layer perspective:   True
Column perspective:  True
Row perspective:     True

Todos os resultados são equivalentes: True


## 10. Verificação da validação de dimensões

No exercício, as funções não devem tentar realizar uma multiplicação quando as dimensões são incompatíveis.

No exemplo abaixo, uma matriz $2 \times 3$ não pode ser multiplicada por uma matriz $2 \times 2$, pois o número de colunas da primeira matriz é diferente do número de linhas da segunda.


In [10]:
A_invalida = np.random.randint(0, 10, size=(2, 3))
B_invalida = np.random.randint(0, 10, size=(2, 2))

try:
    multiplicacao_elemento(A_invalida, B_invalida)
except ValueError as erro:
    print(erro)

Multiplicação inválida: A possui dimensão (2, 3) e B possui dimensão (2, 2). O número de colunas de A deve ser igual ao número de linhas de B.


## Conclusão

As quatro funções implementam diferentes formas de organizar o mesmo produto matricial $C = AB$:

- na **perspectiva por elemento**, cada posição de $C$ é obtida por um produto escalar entre uma linha de $A$ e uma coluna de $B$;
- na **perspectiva por camadas**, $C$ é construída pela soma dos produtos externos entre as colunas de $A$ e as linhas correspondentes de $B$;
- na **perspectiva por colunas**, cada coluna de $C$ é uma combinação linear das colunas de $A$;
- na **perspectiva por linhas**, cada linha de $C$ é uma combinação linear das linhas de $B$.

No teste realizado, as quatro implementações produziram o mesmo resultado do operador padrão `A @ B`. Dessa forma, o experimento confirma que as quatro perspectivas são maneiras diferentes de decompor e organizar computacionalmente a mesma operação de multiplicação de matrizes.

A condição fundamental permanece a mesma em todas as abordagens: **o número de colunas de $A$ deve ser igual ao número de linhas de $B$**.


## Referências

- SOUZA, Vinícius M. A. **Fundamentals of Computational Mathematics — Week 04**. PUCPR, 2026. Material da disciplina.
- BROWNLEE, Jason. **Basics of Linear Algebra for Machine Learning**. Machine Learning Mastery, 2018.
- AGGARWAL, Charu C. **Linear Algebra and Optimization for Machine Learning: A Textbook**. Springer, 2020.
